### ISSUE TITLE
Whole module decides to nuke itself upon restart of VRCFT?

### ISSUE THREAD

**Issue by ChazLayyd** [ykeara/LinkFT#1]
Heres my output.. if it helps? :)

![image](https://github.com/ykeara/LinkFT/assets/134355104/08951205-2508-4c31-a722-b883455350f4)

**Comment by ykeara** [comment]
It appears as though the socket isn't binding.

do not change the VRCFT settings from default (i.e. 9000/01)

do change the steam link settings to enable osc/eye/face/ and osc port to 9015

hopefully that resolves it.
