### ISSUE TITLE
Eye dilation defaults to full constriction

### ISSUE THREAD

**Issue by Saberpeep** [ykeara/LinkFT#2]
Current behavior:
 The eye dilation value is at the minimum at all times (fully constricted).

Expected behavior:
 The Quest Pro does not capture eye dilation, so the dilation should default to the middle of the range.
 (see VD for reference)

**Comment by ykeara** [comment]
I'll have to look into this more.

I see what the VD module is doing, and can copy it, wondering if this is the correct behavior we should expect from VRCFT/VRChat.

I would expect a  0 value to be resting state..... but I can see how with pupil constriction specifically that could be an issue.

**Comment by ykeara** [comment]
This should be fixed as of 0.3.0 release
