### ISSUE TITLE
Issues with manual updates

### ISSUE THREAD

**Issue by ShingenPizza** [ykeara/LinkFT#4]
Hey,
when 1.0.6 was released i tried to manually update it, and i had some isues with it.
IIRC it stopped working, and after VRCFT restart it was uninstalled.
After manually installing it again and restarting VRCFT, it seems to downgrade the module back to 1.0.3:

> [MainStandalone] Information: VRCFT Version 5.1.1.0 initializing...
> [MainStandalone] Information: Initializing OSC...
> [OSC] Debug: OSC Service Initializing
> [OSC] Debug: Binding Sender Client
> [OSC] Debug: OSC Service Initialized with result (True, True)
> [MainStandalone] Information: Initializing main service...
> [VRCFaceTracking.UnifiedTrackingMutator] Debug: Reading configuration...
> [MainStandalone] Debug: Starting OSC update loop...
> [MainStandalone] Debug: Checking for deletion requests for installed modules...
> [MainStandalone] Information: Checking for updates for installed modules...
> [VRCFaceTracking.UnifiedTrackingMutator] Debug: Configuration loaded.
> **[MainStandalone] Information: Updating SteamLink VRCFT Module from 1.0.6 to 1.0.3**
> [VRCFaceTracking.Core.Services.ModuleInstaller] Debug: Uninstalling module 2a8c8080-2a76-46af-bf76-1da7c0127ef8
> [VRCFaceTracking.Core.Services.ModuleInstaller] Information: Uninstalled module 2a8c8080-2a76-46af-bf76-1da7c0127ef8 from C:\Users\Shingen\AppData\Roaming\VRCFaceTracking\CustomLibs\2a8c8080-2a76-46af-bf76-1da7c0127ef8
> [VRCFaceTracking.Core.Services.ModuleInstaller] Information: Installed module 2a8c8080-2a76-46af-bf76-1da7c0127ef8 to C:\Users\Shingen\AppData\Roaming\VRCFaceTracking\CustomLibs\2a8c8080-2a76-46af-bf76-1da7c0127ef8
> [MainStandalone] Information: Initializing modules...

However, when i found and checked the actual file, it seemed to be the new one.

Also, in the module registry it still claims to have been updated in 2023 (the time of v0.4.0 release).
![image](https://github.com/ykeara/LinkFT/assets/19253513/c6e85a2c-00b6-46fb-bb81-36af0bcf240d)

I've prepared this GitHub Issue last month, right after i had these problems, but i wasn't sure to submit it. Currently the module registry correctly shows 1.0.6 (with a still incorrect date though).
I decided to submit that now, because i kinda expect to have the same problems with the future updates, and i'd prefer to avoid them.

**Comment by ykeara** [comment]
yea I think It's a bug with how the module gets updated to the vrcft side I'll reach out and see what exact issue is, Just checked and release  module shows correct time so not really sure what is wrong doesn't appear to be on my end (unless I have date in wrong format or something)


(and yea because of how vrcft works it will pretty much pull from the vrcft server so manual install is hard without changing a few variables.

**Comment by ShingenPizza** [comment]
the date in the module registry appears to be pulled from the module.json file, i have `"LastUpdated": "2023-12-17T18:47:55.533706",` there. if you have something different, then, well, weird. the file gets created when i install it with the "install" button, i don't think it's cached anywhere on my side to pull the old date from.

i see that the module.json in the repository has a proper date, but maybe it's not getting updated in the VRCFT server side?

**Comment by ykeara** [comment]
Yea what I expect, I'm not even 100% sure what happens vrcft server side so I can't tell specifically I shot @benaclejames, It's probably a silly mistake on my end or on server side end think it should be fine, there is currently no functional difference between 1.0.3 and 1.0.6 anyways atm

**Comment by ShingenPizza** [comment]
i mean, it is installing the proper 1.0.6 now, just with a wrong date.
i think that date may be the reason behind the auto-downgrading of a manually installed newer version, although it's the numer that should be more important here... 🤷🏻‍♂️
