### ISSUE TITLE
Virtual Desktop breaking Steam Link Face Tracking.

### ISSUE THREAD

**Issue by Jayconius** [ykeara/LinkFT#6]
Hi, 

I was wondering if you have any information to help me.

I tried Virtual Desktop but when going back to Steam Link LinkFT it no longer makes a connections.
I uninstalled Virtual Desktop and Virtual Desktop services but now it appears it's done something to my system and no longer allows Steam Link Module to connect.

I am convinced Virtual Desktop did this but I can not figure out how the connection is now being blocked. :(

Would you have any idea where to start to figure this out so I can use this module again? I know Virtual Desktop isn't your issue, I'm just wondering if you had an idea why it would be doing it.

I am using the Alternative Port on Steam and Have Face and Eye tracking Enable and OSC. 

I am so at a loss.
TIA! :)

**Comment by ykeara** [comment]
not sure I quite understand

are you having issues the LinkFT module (or w/e it's called in the app?)

or are you having issues with the VD module?


the Steamlink (i.e. this/linkft) module will block other modules from running if it's installed, unfortunately this is just kinda a hard limitation to how steamlink sends the FT data (or rather it's a compromise for UX)

so few steps maybe to help.

1. when launching VRCFT which module is loaded (should say at home tab) Steamlink VRCFT module is us.
2. if the right module is loaded the easy way to check if you have connection is to see if messages are going back and forth via VRCFT


Note: this module is hardcoded to ports 9014/15? I think (would have to double check) so from the steamlink settings need to have those ports set from the default.

OTHER APPS CANNOT USE Those ports or you will get undefined behavior, I.E. if you have VRCFT set to those ports it can cause issues


Overall our communication stack looks like
Steamlink->LinkFT Module ->VRCFT->VRC

Steamlink->Link FT Module is port 9014/15 I think without doublechecking [make sure in steam's settings this port is selected]
LinkFT Module->VRCFT - internal and not a port
VRCFT->VRC is 9000/9001 by default

the VD module I believe uses memory mapping so it also doesn't use a port.

**Comment by Jayconius** [comment]
Hi,

Thank you. I managed to get it working again. I changed the IP from the loopback IP 127.0.0.1 to my lan IP and it magically started working again but it appears I can't use the loopback IP ever again for some reason after using VD. I installed TPCView to see if anything was using the port but I wasn't getting any luck. I have no idea why. 

Thank you for clarifying the settings. :)
